<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace detalika\delivery\models\base;

use Yii;

/**
 * This is the base-model class for table "delivery_partners".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property boolean $visible
 *
 * @property \detalika\delivery\models\GoodsGood[] $goodsGoods
 * @property string $aliasModel
 */
abstract class Partner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'delivery_partners';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created', 'updated'], 'safe'],
            [['name'], 'required'],
            [['visible'], 'boolean'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('modules/delivery/', 'ID'),
            'created' => Yii::t('modules/delivery/', 'Created'),
            'updated' => Yii::t('modules/delivery/', 'Updated'),
            'name' => Yii::t('modules/delivery/', 'Name'),
            'visible' => Yii::t('modules/delivery/', 'Visible'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoodsGoods()
    {
        return $this->hasMany(\detalika\delivery\models\GoodsGood::className(), ['delivery_partner_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \detalika\delivery\queries\PartnerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \detalika\delivery\queries\PartnerQuery(get_called_class());
    }


}
