<?php

namespace detalika\clients\models;

use detalika\clients\models\base\Source as BaseSource;
use execut\crudFields\Behavior;

class Source extends BaseSource
{
    public static function find()
    {
        return parent::find(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return $this->name;
    }

    public static function findByPk($id)
    {
        return Source::findOne(['id' => $id]);
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['fields'] = [
            'class' => Behavior::className(),
            'fields' => [
                'name' => [
                    'attribute' => 'name',
                ],
            ],
        ];

        return $behaviors;
    }

    public function getFormFields()
    {
        $fields = $this->getBehavior('fields')->getFormFields();

        return $fields;
    }
}    
